### ISSUE TITLE
Brute force CAN?

### ISSUE THREAD

**Issue by artizirk** [TanelOrumaa/Estonian-ID-card-mobile-authenticator-POC#13]
Totally random but, how fast can you brute force the CAN? Its like only a 6 digit number.

Also somewhat related but, does eID provide any unique ID before PACE session that can be used to build a mapping between the card and CAN?

**Comment by martinpaljak** [comment]
Obviously there are delays introduced for bruteforce. Here the whole idea of pace is to provide "anonymous RF layer"

**Comment by Asdervbn** [comment]
As per [this paper](https://comserv.cs.ut.ee/home/files/Kivivare_ComputerScience_2020.pdf?study=ATILoputoo&reference=87E6E1A14B9BC99ED47533B597228A376CE608E1), brute forcing the CAN isn't feasible.

eID can't provide such an ID simply because it has no way of knowing anything identifying about the card before PACE has been established.

**Comment by Asdervbn** [comment]
As per [this paper](https://comserv.cs.ut.ee/home/files/Kivivare_ComputerScience_2020.pdf?study=ATILoputoo&reference=87E6E1A14B9BC99ED47533B597228A376CE608E1), brute forcing the CAN isn't feasible.

eID can't provide such an ID simply because it has no way of knowing anything identifying about the card before PACE has been established.
